const factories={
 aluminum:{name:"铝厂",tag:"AL-04",summary:"600 铝土矿/min，湿法氧化铝与纯铝锭体系；不引入二氧化硅。",inputs:["铝土矿 600","煤 320","铜矿 240"],outputs:["铝外壳 225","铝板 240","电池 20"],transport:"双线铁路 · 无人机"},
 electronics:{name:"电子厂",tag:"EL-07",summary:"钦基电路板、计算机、高速连接器、无线电控制单元与超级计算机专线。",inputs:["钦锭 138+","塑料 110+","铝外壳 90"],outputs:["计算机 15/2","RCU 9/2","超级计算机 15/8"],transport:"铁路 · 传送带"},
 heavy:{name:"重工业区",tag:"HV-03",summary:"水洗铁锭、坚固钢锭与两台重型模块化框架制造机组成的闭环产线。",inputs:["煤 230","水洗铁矿","湿混凝土 80"],outputs:["HMF 45/8","余煤 730","模块化框架"],transport:"卡车 · 传送带"},
 oil:{name:"石油区",tag:"OI-02",summary:"重油残渣与稀释燃油体系：一半支撑橡塑，一半提供稳定燃油发电。",inputs:["原油 480","水 1440"],outputs:["塑料 480","橡胶 240","电力 8000 MW"],transport:"管道 · 铁路"}
};
const flows=[["石油区","塑料 / 橡胶","电子厂","铁路","480 / 240"],["铝厂","铝外壳","电子厂","铁路","225"],["重工煤矿区","煤","重工业区","传送带","230"],["外部石灰石","湿混凝土","重工业区","卡车","80"],["铝厂","电池","无人机仓","无人机","20"]];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function selectFactory(id){const f=factories[id];$$('[data-factory]').forEach(x=>x.classList.toggle('selected',x.dataset.factory===id));$('#detail-tag').textContent=f.tag;$('#detail-name').textContent=f.name;$('#detail-summary').textContent=f.summary;$('#detail-inputs').innerHTML=f.inputs.map(x=>`<span>${x}</span>`).join('');$('#detail-outputs').innerHTML=f.outputs.map(x=>`<span>${x}</span>`).join('');$('#detail-transport').textContent=f.transport;$$('.district-card').forEach(x=>x.classList.toggle('active',x.dataset.factory===id));}
function renderDistricts(){const out=Object.entries(factories).map(([id,f])=>`<button class="district-card" data-factory="${id}"><span class="card-code">${f.tag}</span><h3>${f.name}</h3><p>${f.summary}</p><div class="card-output"><small>核心产出</small><b>${f.outputs[0]} / min</b></div><footer><span>${f.transport}</span><i>↗</i></footer></button>`).join('');$('#district-grid').innerHTML=out;$$('.district-card').forEach(x=>x.addEventListener('click',()=>selectFactory(x.dataset.factory)));}
function renderFlows(filter='全部'){const rows=filter==='全部'?flows:flows.filter(r=>r[3]===filter);$('#flow-rows').innerHTML=rows.map(r=>`<div class="flow-row"><span>${r[0]}</span><span>${r[1]}</span><span><i class="arrow">→</i>${r[2]}</span><span>${r[3]}</span><span>${r[4]}</span></div>`).join('');}
$$('[data-jump]').forEach(x=>x.addEventListener('click',()=>document.getElementById(x.dataset.jump).scrollIntoView({behavior:'smooth'})));$$('.map-node').forEach(x=>x.addEventListener('click',()=>selectFactory(x.dataset.factory)));$$('[data-filter]').forEach(x=>x.addEventListener('click',()=>{$$('[data-filter]').forEach(b=>b.classList.remove('active'));x.classList.add('active');renderFlows(x.dataset.filter)}));
renderDistricts();renderFlows();selectFactory('aluminum');
