const F=[
{id:'main',name:'主基地综合工业区',tag:'CORE-01',machines:129,coord:'268109, -253521',pos:'mark-main',summary:'全存档最大的综合制造区，包含基础铁铜件、坚固钢锭、电梯件、定子、马达、弹药与 SAM 产线。',recipes:['铁锭×24','电线×14','铁棒×10','螺丝×9','坚固钢锭×8','钢管×6','钢梁×5','定子×4','马达×1'],infra:['55 构造器','32 熔炉','18 装配器','8 铸造厂','7 Mk.2 矿机'],transport:'卡车物流中枢 · 太空电梯'},
{id:'oil',name:'石油·橡塑·燃油区',tag:'OIL-02',machines:112,coord:'139654, -248532',pos:'mark-oil',summary:'左上沿海的石油工业群，打包水与燃料循环支撑橡塑生产和大规模燃油发电。',recipes:['打包水×23','解包燃油×23','燃油发电机×32','抽水机×16','原油增压井×2'],infra:['48 打包机','32 燃油发电机','16 抽水机','3 卡车站','3 火车站'],transport:'管道 · 铁路 · 卡车'},
{id:'electronics',name:'电子厂·超级计算机专线',tag:'ELEC-03',machines:72,coord:'314931, -252714',pos:'mark-electronics',summary:'钦基电子体系与超级计算机专线，输入钦锭、塑料、橡胶、石英晶体、二氧化硅和铝壳。',recipes:['快速线×21','钦基电路板×11','钦基计算机×4','AI限制器×3','晶振×2','高速连接器×3','超级计算机×1'],infra:['27 构造器','14 装配器','11 制造机','18 命名卡车站'],transport:'卡车站阵列 · 主基地内线'},
{id:'starter',name:'早期基础件基地',tag:'BASE-04',machines:56,coord:'275962, -208776',pos:'mark-starter',summary:'太空电梯附近的早期基地，生产铁板、铁棒、螺丝、加强铁板、铜锭、电线、电缆与模块化框架。',recipes:['铁锭×8','铁板×6','铁棒×6','螺丝×6','铜锭×4','加强铁板×3','模块化框架×1'],infra:['25 构造器','12 熔炉','4 装配器','12 自动化生物质发电机'],transport:'传送带 · 太空电梯'},
{id:'coal',name:'煤炭发电站',tag:'POWER-05',machines:46,coord:'204263, -261404',pos:'mark-coal',summary:'石油区与主基地之间的基础电力站，两座 Mk.2 煤矿与十二台抽水机供给三十二台煤电机。',recipes:['煤电机×32','抽水机×12','Mk.2矿机×2'],infra:['32 煤炭发电机','12 抽水机','2 Mk.2 矿机'],transport:'传送带 · 管道'},
{id:'heavy',name:'重型模块化框架厂',tag:'HMF-06',machines:45,coord:'320341, -217855',pos:'mark-heavy',summary:'水洗铁锭、铁制电线、坚固钢锭、钢管、钢筋混凝土梁与重型模块化框架组成的闭环重工厂。',recipes:['钢管×12','坚固钢锭×6','模块化框架×5','钢筋混凝土梁×5','铁线×3','HMF×2'],infra:['17 构造器','12 装配器','6 铸造厂','2 制造机','1 火车站'],transport:'铁路 · 卡车 · 传送带'},
{id:'aluminum',name:'铝材·电池联合厂',tag:'AL-07',machines:32,coord:'256498, 56958',pos:'mark-aluminum',summary:'东南沼泽中的铝材基地，煤由铁路输入；纯铝锭、复合铝板、铝壳和电池在同一区域生产。',recipes:['纯铝锭×16','复合铝板×6','铝壳×2','电池×2'],infra:['16 熔炉','8 装配器','2 调合机','3 Mk.2 矿机','2 火车站'],transport:'双线铁路 · 无人机 · 管道'},
{id:'quartz',name:'石英加工区',tag:'QZ-08',machines:23,coord:'307929, -300582',pos:'mark-quartz',summary:'北部独立石英前哨，将原石英拆分为二氧化硅与石英晶体，再通过卡车送往电子厂。',recipes:['二氧化硅×11','石英晶体×8'],infra:['19 构造器','2 Mk.2 矿机','2 卡车站'],transport:'卡车 · 主基地电子线'},
{id:'nitrogen',name:'氮气与冷却系统站',tag:'N2-09',machines:1,coord:'89299, 101408',pos:'mark-nitrogen',summary:'南部铁路终端，承担后期冷却系统物料集散。',recipes:['氮气','铝壳','橡胶','冷却系统'],infra:['1 命名火车站','高架铁路终端'],transport:'铁路'}];
const flows=[['石油区','塑料 / 橡胶 / 燃料','主基地与电子厂','铁路','480 / 240 / —'],['石英区','石英晶体 / 二氧化硅','电子厂','卡车','144 / 400'],['铝厂','铝材','主基地铝下货','铁路','225 / 240'],['煤炭矿区','煤炭','铝厂煤炭下货','铁路','320'],['外部补给站','混凝土 / 水 / 煤','重型框架厂','卡车','80 / 600 / 230'],['铝厂','电池','无人机网络','无人机','20'],['氮气站','氮气 / 铝壳 / 橡胶','冷却系统线','铁路','待扩建']];
const stations=['石油塑胶上货','石油塑料上货','石油燃料上货','主基地铝下货','铝材上货','煤炭下货','煤炭上货1','石英晶体上货','钦锭下货','橡胶下货','塑料下货','二氧化硅下货','超级计算机上货','电池上货','氮气厂-铝壳-橡胶-冷却系统'];
let selected='main',filter='全部';const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function detail(){const f=F.find(x=>x.id===selected);$('#save-detail').innerHTML=`<div class="detail-head"><span>${f.tag}</span><b>${f.machines} 设施</b></div><h3>${f.name}</h3><p>${f.summary}</p><small>中心坐标</small><code>${f.coord}</code><div class="recipe-list">${f.recipes.map(x=>`<span>${x}</span>`).join('')}</div><footer>${f.transport}</footer>`;$$('[data-factory]').forEach(x=>x.classList.toggle('selected',x.dataset.factory===selected));}
function rows(){const r=filter==='全部'?flows:flows.filter(x=>x[3]===filter);$('#flow-rows').innerHTML=r.map(x=>`<div class="flow-row">${x.map((v,i)=>`<span>${i===2?'<i class="arrow">→</i>':''}${v}</span>`).join('')}</div>`).join('');$$('[data-filter]').forEach(x=>x.classList.toggle('active',x.dataset.filter===filter));}
document.getElementById('app').innerHTML=`<section class="hero" id="overview"><div class="hero-shade"></div><nav class="topbar" aria-label="主导航"><button class="brand" data-jump="overview" aria-label="返回总览"><span></span><span></span><span></span><span></span></button><div class="nav-links"><button class="active" data-jump="overview">总览</button><button data-jump="real-map">地图</button><button data-jump="districts">厂区</button><button data-jump="logistics">物流</button><button data-jump="archive">存档</button></div><div class="running"><span>存档已解析</span><i></i></div></nav><div class="hero-copy"><p class="eyebrow">2026SPRING · BUILD 495413 · MODDED SAVE</p><h1>真实存档<br>工业档案</h1><div class="tier-badge">SAVE V60 <span>///</span></div><div class="hero-metrics"><div><b>55,132</b><span>存档对象</span></div><div><b>584</b><span>生产与资源设施</span></div><div><b>79.1h</b><span>游戏时长</span></div></div><button class="primary" data-jump="real-map">进入真实地图 <span>→</span></button></div><div class="hero-facts"><span>9 个主要工业分区</span><span>15 个命名物流站</span><span>3 个启用模组</span></div><div class="scroll-cue">数据直接读取自 2026Spring_autosave_1.sav ↓</div></section>
<section class="section real-map" id="real-map"><header class="section-title"><div><p>01 · REAL SAVE MAP</p><h2>真实工厂地图</h2></div><span>点击地图标记查看存档内实际配方与设施</span></header><div class="save-map-layout"><div class="save-map-wrap"><img src="https://satisfactory-factory-atlas.largeoyos.chatgpt.site/real-save-map.png" alt="2026Spring 存档真实地图">${F.map(f=>`<button class="save-marker ${f.pos}" data-factory="${f.id}" aria-label="查看${f.name}"><b>${f.tag.split('-')[0]}</b><span>${f.name}</span></button>`).join('')}</div><aside class="save-detail" id="save-detail"></aside></div></section>
<section class="section districts" id="districts"><header class="section-title"><div><p>02 · FACTORY CLUSTERS</p><h2>九大工业分区</h2></div><span>按 120 米设施邻接关系从存档自动聚类</span></header><div class="district-grid">${F.map(f=>`<button class="district-card" data-factory="${f.id}"><span class="card-code">${f.tag} · ${f.machines} FACILITIES</span><h3>${f.name}</h3><p>${f.summary}</p><div class="machine-tags">${f.infra.map(x=>`<span>${x}</span>`).join('')}</div><footer><span>${f.transport}</span><i>↗</i></footer></button>`).join('')}</div></section>
<section class="section logistics" id="logistics"><header class="section-title"><div><p>03 · LOGISTICS LEDGER</p><h2>真实物流网络</h2></div><div class="filters">${['全部','铁路','卡车','无人机'].map(x=>`<button data-filter="${x}">${x}</button>`).join('')}</div></header><div class="flow-table"><div class="flow-row heading"><span>起点</span><span>货物</span><span>终点</span><span>方式</span><span>流量 / min</span></div><div id="flow-rows"></div></div><div class="station-cloud">${stations.map(x=>`<span>${x}</span>`).join('')}</div></section>
<section class="section stats" id="archive"><header class="section-title"><div><p>04 · SAVE TELEMETRY</p><h2>存档遥测</h2></div><span>解析自 Save Version 60</span></header><div class="stat-grid"><article class="power-card"><p>生产设施总量</p><b>584</b><div class="power-bar"><i style="width:88%"></i></div><footer><span>覆盖生产、采矿、发电与运输站</span><em>已解析</em></footer></article><article><span>存档对象</span><b>55,132</b><small>全世界分区对象</small></article><article><span>运行时间</span><b>79.1</b><small>小时</small></article><article><span>最大厂区</span><b>129</b><small>主基地综合区</small></article><article><span>燃油发电机</span><b>32</b><small>石油工业区</small></article></div><div class="archive-grid"><article><p>存档身份</p><dl><div><dt>会话</dt><dd>2026Spring</dd></div><div><dt>Build</dt><dd>495413</dd></div><div><dt>Save Version</dt><dd>60</dd></div><div><dt>模式</dt><dd>单人 · 非创造</dd></div></dl></article><article><p>已启用模组</p><ul><li>Additional 300 Inventory Slots 6.2.9</li><li>MinoDabsCommonLib 1.1.5</li><li>Smart! 33.3.0</li></ul></article><article><p>关键里程碑</p><ul><li>太空电梯件已完成</li><li>超级计算机与无线电控制单元已产</li><li>铝材与电池联合厂运行中</li><li>铁路、卡车与无人机网络已成形</li></ul></article></div></section><section class="section milestones"><header class="section-title"><div><p>05 · NEXT PHASE</p><h2>下一阶段</h2></div><span>以真实存档现状为起点</span></header><div class="next-build"><p>EXPANSION PLAN</p><h3>完善氮气冷却系统与后期太空电梯供应链</h3><span>保留主基地钢、马达和定子产线；继续利用现有双线铁路、铝材火车站与电池无人机网络。</span></div></section><footer class="site-footer"><span>FICSIT SAVE ARCHIVE · 2026SPRING · BUILD 495413</span><span>最后解析：2026.07.12</span></footer>`;
$$('[data-jump]').forEach(x=>x.onclick=()=>document.getElementById(x.dataset.jump).scrollIntoView({behavior:'smooth'}));$$('[data-factory]').forEach(x=>x.onclick=()=>{selected=x.dataset.factory;detail();if(x.classList.contains('district-card'))document.getElementById('real-map').scrollIntoView({behavior:'smooth'})});$$('[data-filter]').forEach(x=>x.onclick=()=>{filter=x.dataset.filter;rows()});detail();rows();
