const page=document.body.dataset.page,$=s=>document.querySelector(s),link=id=>byId(id)?`/factory/?id=${id}`:'#',img=(src,alt='')=>src?`<img class="item-icon" src="${src}" alt="${alt}">`:'';
const nav=`<nav><a href="/" class="brand">FICSIT // V13</a><div><a href="/map/">地图</a><a href="/factories/">厂区</a><a href="/logistics/">物流</a><a href="/power/">电力</a><a href="/archive/">存档</a></div><span>BUILD 495413</span></nav>`,foot=`<footer>2026SPRING · /min · 分数口径</footer>`,head=(n,t,s='')=>`${nav}<header><small>${n}</small><h1>${t}</h1><p>${s}</p></header>`;
if(page==='home')$('#app').innerHTML=`${nav}<section class="hero"><div><small>2026SPRING · V13 DATA BOARD</small><h1>真实存档<br>工业总控台</h1><p>从矿机、运输、中间配方到最终去向，逐级追踪全图生产链。</p><section class="metrics"><b>9<em>核心厂区</em></b><b>10,400 MW<em>毛发电</em></b><b>79.1h<em>游戏时长</em></b></section><a class="cta" href="/map/">进入真实地图 →</a></div></section><section class="quick"><a href="/map/"><b>真实地图</b><span>悬浮看产出，点击进入厂区</span></a><a href="/logistics/"><b>物流网络</b><span>追踪来源、流量与去向</span></a><a href="/power/"><b>电力分析</b><span>毛发电与扩容约束</span></a></section>${foot}`;
if(page==='map')$('#app').innerHTML=`${head('01 · REAL SAVE MAP','真实工厂地图','悬浮显示产品，点击进入产线分析')}<main class="map"><div class="mapbox"><img src="/real-save-map.jpg" alt="2026Spring 存档地图">${factories.map(f=>`<a class="marker ${f.pos}" href="${link(f.id)}"><b>${f.tag}</b><span>${f.name}</span><aside>${img(f.icon,f.name)}<strong>产出</strong>${f.products.slice(0,5).map(x=>`<i>${x}</i>`).join('')}</aside></a>`).join('')}</div></main>${foot}`;
if(page==='factories')$('#app').innerHTML=`${head('02 · FACTORY HIERARCHY','厂区层级','每个厂区都有独立页面；每条配方均标明默认或替代。')}<main class="cards">${factories.map(f=>`<a href="${link(f.id)}">${img(f.icon,f.name)}<small>${f.tag}</small><h2>${f.name}</h2><p>${f.summary}</p><div>${f.products.slice(0,4).map(x=>`<i>${x}</i>`).join('')}</div><b>查看子产线与配方 →</b></a>`).join('')}</main>${foot}`;
if(page==='factory'){const f=byId(new URLSearchParams(location.search).get('id'))||factories[0];$('#app').innerHTML=`${nav}<header><small>${f.tag} · PRODUCTION DOSSIER</small><h1>${img(f.icon,f.name)}${f.name}</h1><p>${f.summary}</p></header><main class="dossier"><section class="legend"><b>配方标记</b><span>默认：游戏标准配方</span><span>替代：当前存档所选替代配方</span><span>开采参数已列在原材料卡内</span></section><h2>原材料与来源</h2><section class="io">${f.inputs.map(x=>`<article><small>进货 / 开采</small><h3>${x[0]}</h3><b>${x[1]} /min</b><p>${x[2]} · ${x[3]}</p>${x[4]!==f.id&&byId(x[4])?`<a href="${link(x[4])}">跳转到供货地 →</a>`:''}</article>`).join('')}</section><h2>厂内子分区与生产链</h2><section class="chain">${f.chain.map((x,i)=>`<article><div class="chain-title">${img(x.icon,x.name)}<small>${String(i+1).padStart(2,'0')} · ${x.zone}</small></div><h3>${x.name}</h3><mark class="recipe ${x.recipe.startsWith('默认')?'default':'alternate'}">${x.recipe}</mark><p><em>输入</em>${x.input}</p><b>↓</b><p><em>输出</em>${x.output}</p></article>`).join('')}</section><h2>产出与去向</h2><section class="io">${f.outputs.map(x=>`<article><small>${x[3]==='storage'?'仓储':'下游需求'}</small><h3>${x[0]}</h3><b>${x[1]} /min</b><p>${x[2]}</p>${byId(x[3])?`<a href="${link(x[3])}">跳转到需求地 →</a>`:''}</article>`).join('')}</section></main>${foot}`}
if(page==='logistics'){const rs=factories.flatMap(f=>f.outputs.filter(x=>byId(x[3])).map(x=>[f,x]));$('#app').innerHTML=`${head('03 · LOGISTICS','物流关系','点击两端进入对应厂区')}<main class="routes">${rs.map(r=>`<article><a href="${link(r[0].id)}">${r[0].name}</a><div><b>${r[1][1]}</b><span>${r[1][2]} →</span></div><a href="${link(r[1][3])}">${r[1][0]}</a></article>`).join('')}</main>${foot}`}
if(page==='power')$('#app').innerHTML=`${head('04 · POWER ANALYSIS','电力分析','当前只能确定毛发电；净余量需实时功耗')}<main class="power"><section><small>全图毛发电</small><b>10,400 MW</b></section><a href="${link('oil')}"><h2>燃油发电</h2><b>8,000 MW · 约77%</b><i style="width:77%"></i></a><a href="${link('coal')}"><h2>燃煤发电</h2><b>2,400 MW · 约23%</b><i style="width:23%"></i></a><aside><h2>扩容约束</h2><p>煤电煤矿已吃满，两口发电/橡塑油井也已吃满。需要新增资源点才能扩大现有结构。</p></aside></main>${foot}`;
if(page==='archive')$('#app').innerHTML=`${head('05 · SAVE & AUDIT','存档与V13核对')}<main class="audit"><article><h2>存档</h2><p>2026Spring · Build 495413 · Save V60</p><p>79.1小时 · 55,132对象 · 584设施</p></article><article><h2>核对通过</h2><p>铁矿3926/3、煤1355、石灰石600。</p><p>塑料余14195/56、橡胶余315/4、钦锭余1833/28。</p><p>铝壳余95、混凝土余109、毛发电10400MW。</p></article><article><h2>待补充</h2><p>氮气井流量、冷却系统机器数、仓库位置、电网实时功耗。</p></article></main>${foot}`;
